### ISSUE TITLE
Remaining icon in status bar after uninstall

### ISSUE THREAD

**Issue by Johannes-van-der-Merwe** [be5invis/vscode-custom-css#143] opened 2021-05-16 11:29 UTC
![2021-05-16 13_19_58-](https://user-images.githubusercontent.com/37486278/118395302-d78ad580-b649-11eb-9396-80566e68f932.png) 

Just a note: Vscode does display the corrupt notification with this.

**Comment by be5invis** [comment] 2021-05-16 22:32
Because this extension modifies VSCode itself, you need to reinstall the extension, disable custom CSS then uninstall it.
Closing as by design.

**Closed by be5invis** 2021-05-16 22:32 UTC

**Comment by albert-ying** [comment] 2022-06-29 04:16
I have the same problem. The icon remains there even after I reinstall the extension and disable the icon in the setting

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/59846322/176350467-990caf57-f232-44f1-9328-725f5983c342.png">

**Comment by hyphast** [comment] 2024-05-12 20:48
You can just run command palette and execute: `extension.uninstallCustomCSS`
