### ISSUE TITLE
Stylesheet is not loading

### ISSUE THREAD

**Issue by DanaJDavis** [be5invis/vscode-custom-css#25] opened 2017-12-01 21:39 UTC
This is what I have in my custom settings:
    "vscode_custom_css.imports": ["file:///Users/danadavis/.vscode/style.css"]

When I cmd+click on the link, it opens the file. But when I open dev tools from 'Help>Toggle Developer Tools", I can't see my stylesheet loading in the Network tab. I also don't have any console errors.

**Comment by israellamarr** [comment] 2017-12-09 03:03
I am encountering this same exact behavior.  I cannot get the custom file to load into the app, the file links correctly and no errors are present.

**Comment by kissu** [comment] 2017-12-09 04:00
@DanaJDavis had the same issue. Realized I'm trash because I forgot to `Hit 'CMD + shift + P' and type 'Enable Custom CSS and JS'`...

**Comment by israellamarr** [comment] 2017-12-09 04:07
Haha yeah i actually did the same thing. Except I wasn’t using the correct classes either.

**Comment by kissu** [comment] 2017-12-09 06:38
@DanaJDavis if you're still interested, I wrote a little markdown to show how I made it work and why it can still be buggy on your side. 😉 

It's 80% similar to what @israellamarr linked tho. 💯  
https://github.com/kissu/dotfiles

**Comment by be5invis** [comment] 2017-12-09 14:55
This extension modifies Code itself so it could not be implemented as "save config then enable". You have to manually enable the styles with the command.
Closed as by design.

**Closed by be5invis** 2017-12-09 14:55 UTC
